
#########################
### Authentication ...
#########################

### Sign up -> SUCCESSFULL
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "username": "FS20_03_TestUser2",
  "password": "FS20_03_TestPwd2"
}

###

### Sign in -> SUCCESSFULL
POST http://localhost:8080/auth/signin
Content-Type: application/json

{
  "username": "FS20_03_TestUser2",
  "password": "FS20_03_TestPwd2"
}

> {%
    client.global.set("auth_token", response.body.accessToken);
%}

#######################
### Person ...
#######################

### Get all persons -> SUCCESSFULL
GET http://localhost:8080/persons
Authorization: Bearer {{auth_token}}

###

### Get person by id -> SUCCESSFULL
GET http://localhost:8080/persons/12
Authorization: Bearer {{auth_token}}

###

### Patch person by id -> SUCCESSFULL
PATCH http://localhost:8080/persons/12
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "username": "FS20_03_TestUser"
}

###

### Delete person by id -> SUCCESSFULL -> Only if person has no items
DELETE http://localhost:8080/persons/5
Authorization: Bearer {{auth_token}}

#######################
### Item ...
#######################

### Create item -> SUCCESSFULL
POST http://localhost:8080/items
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "FS20_03_TestItem2",
  "description": "FS20_03_ItemDescription2",
  "personId": 12,
  "tagIds": 12
}

###

### Get Item by id -> SUCCESSFULL
GET http://localhost:8080/items/11
Authorization: Bearer {{auth_token}}

###

### Get all Items -> SUCCESSFULL
GET http://localhost:8080/items
Authorization: Bearer {{auth_token}}

###

### Get all Items by name -> SUCCESSFULL
GET http://localhost:8080/items?name=FS20_03_TestItem
Authorization: Bearer {{auth_token}}

###

### Get all Items by tag name -> SUCCESSFULL
GET http://localhost:8080/items/item?tagName=FS20_03_TestTag2
Authorization: Bearer {{auth_token}}

###

### Delete Item by id -> SUCCESSFULL
DELETE http://localhost:8080/items/17
Authorization: Bearer {{auth_token}}

#######################
### Tag ...
#######################

### Create Tag -> SUCCESSFULL
POST http://localhost:8080/tags
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "FS20_03_TestTag",
  "itemIds": 18
}

###

### Get all Tags -> SUCCESSFULL
GET http://localhost:8080/tags/tag
Authorization: Bearer {{auth_token}}

###

### Get Tags by name -> SUCCESSFULL
GET http://localhost:8080/tags/tag?name=FS20_03_patchedTag2
Authorization: Bearer {{auth_token}}

###

### Patch/update tag -> SUCCESSFULL
PATCH http://localhost:8080/tags/19
Authorization: Bearer {{auth_token}}
Content-Type: application/json

{
  "name": "FS20_03_patchedTag2"
}

###

### Get Tag by id -> SUCCESSFULL
GET http://localhost:8080/tags/19
Authorization: Bearer {{auth_token}}

###

### Delete tag by id -> SUCCESSFULL
DELETE http://localhost:8080/tags/22
Authorization: Bearer {{auth_token}}
